class PlayerWorker
    include Sidekiq::Worker
    sidekiq_options :queue => :default

    GAME_MODES = {
        'solo': 'matchesSolo',
        'solo-fpp': 'matchSoloFPP',
        'duo': 'matchesDuo',
        'duo-fpp': 'matchesDuoFPP',
        'squad': 'matchesSquad',
        'squad-fpp': 'matchesSquadFPP',
    }
    
    def perform(player_id)
        player = Player.find(player_id)
        req = RestClient.get "https://api.playbattlegrounds.com/shards/pc-na/seasons", {accept: :json, Authorization: "Bearer #{Rails.application.secrets.PUBG_SECRET}"}
        body = JSON.parse(req.body)
        current_season_id = ''
        body['data'].each { |k|  current_season_id = k['id'] if k['attributes']['isCurrentSeason'] }

        req = RestClient.get "https://api.playbattlegrounds.com/shards/pc-na/players/" + player.player_id + "/seasons/" + current_season_id,
            {accept: :json, Authorization: "Bearer #{Rails.application.secrets.PUBG_SECRET}"}
        body = JSON.parse(req.body)

        body['data']['attributes']['gameModeStats'].each do |game_mode|
            Season.build_season(player, game_mode) unless body['data']['relationships'][GAME_MODES[game_mode[0].to_sym]].nil?
        end
    end

end

# {"gameModeStats"
# {"duo"
# {"assists"
# 0, "boosts"
# 0, "dBNOs"
# 0, "dailyKills"
# 0, "damageDealt"
# 0, "days"
# 0, "headshotKills"
# 0, "heals"
# 0, "killPoints"
# 0, "kills"
# 0, "longestKill"
# 0, "longestTimeSurvived"
# 0, "losses"
# 0, "maxKillStreaks"
# 0, "mostSurvivalTime"
# 0, "revives"
# 0, "rideDistance"
# 0, "roadKills"
# 0, "roundMostKills"
# 0, "roundsPlayed"
# 0, "suicides"
# 0, "teamKills"
# 0, "timeSurvived"
# 0, "top10s"
# 0, "vehicleDestroys"
# 0, "walkDistance"
# 0, "weaponsAcquired"
# 0, "weeklyKills"
# 0, "winPoints"
# 0, "wins"
# 0}, "duo-fpp"
# {"assists"
# 0, "boosts"
# 0, "dBNOs"
# 0, "dailyKills"
# 0, "damageDealt"
# 0, "days"
# 0, "headshotKills"
# 0, "heals"
# 0, "killPoints"
# 0, "kills"
# 0, "longestKill"
# 0, "longestTimeSurvived"
# 0, "losses"
# 0, "maxKillStreaks"
# 0, "mostSurvivalTime"
# 0, "revives"
# 0, "rideDistance"
# 0, "roadKills"
# 0, "roundMostKills"
# 0, "roundsPlayed"
# 0, "suicides"
# 0, "teamKills"
# 0, "timeSurvived"
# 0, "top10s"
# 0, "vehicleDestroys"
# 0, "walkDistance"
# 0, "weaponsAcquired"
# 0, "weeklyKills"
# 0, "winPoints"
# 0, "wins"
# 0}, "solo"
# {"assists"
# 0, "boosts"
# 0, "dBNOs"
# 0, "dailyKills"
# 0, "damageDealt"
# 0, "days"
# 0, "headshotKills"
# 0, "heals"
# 0, "killPoints"
# 0, "kills"
# 0, "longestKill"
# 0, "longestTimeSurvived"
# 0, "losses"
# 0, "maxKillStreaks"
# 0, "mostSurvivalTime"
# 0, "revives"
# 0, "rideDistance"
# 0, "roadKills"
# 0, "roundMostKills"
# 0, "roundsPlayed"
# 0, "suicides"
# 0, "teamKills"
# 0, "timeSurvived"
# 0, "top10s"
# 0, "vehicleDestroys"
# 0, "walkDistance"
# 0, "weaponsAcquired"
# 0, "weeklyKills"
# 0, "winPoints"
# 0, "wins"
# 0}, "solo-fpp"
# {"assists"
# 0, "boosts"
# 0, "dBNOs"
# 0, "dailyKills"
# 0, "damageDealt"
# 0, "days"
# 0, "headshotKills"
# 0, "heals"
# 0, "killPoints"
# 0, "kills"
# 0, "longestKill"
# 0, "longestTimeSurvived"
# 0, "losses"
# 0, "maxKillStreaks"
# 0, "mostSurvivalTime"
# 0, "revives"
# 0, "rideDistance"
# 0, "roadKills"
# 0, "roundMostKills"
# 0, "roundsPlayed"
# 0, "suicides"
# 0, "teamKills"
# 0, "timeSurvived"
# 0, "top10s"
# 0, "vehicleDestroys"
# 0, "walkDistance"
# 0, "weaponsAcquired"
# 0, "weeklyKills"
# 0, "winPoints"
# 0, "wins"
# 0}, "squad"
# {"assists"
# 0, "boosts"
# 0, "dBNOs"
# 0, "dailyKills"
# 0, "damageDealt"
# 0, "days"
# 0, "headshotKills"
# 0, "heals"
# 0, "killPoints"
# 0, "kills"
# 0, "longestKill"
# 0, "longestTimeSurvived"
# 0, "losses"
# 0, "maxKillStreaks"
# 0, "mostSurvivalTime"
# 0, "revives"
# 0, "rideDistance"
# 0, "roadKills"
# 0, "roundMostKills"
# 0, "roundsPlayed"
# 0, "suicides"
# 0, "teamKills"
# 0, "timeSurvived"
# 0, "top10s"
# 0, "vehicleDestroys"
# 0, "walkDistance"
# 0, "weaponsAcquired"
# 0, "weeklyKills"
# 0, "winPoints"
# 0, "wins"
# 0}, "squad-fpp"
# {"assists"
# 0, "boosts"
# 0, "dBNOs"
# 0, "dailyKills"
# 0, "damageDealt"
# 0, "days"
# 0, "headshotKills"
# 0, "heals"
# 0, "killPoints"
# 0, "kills"
# 0, "longestKill"
# 0, "longestTimeSurvived"
# 0, "losses"
# 0, "maxKillStreaks"
# 0, "mostSurvivalTime"
# 0, "revives"
# 0, "rideDistance"
# 0, "roadKills"
# 0, "roundMostKills"
# 0, "roundsPlayed"
# 0, "suicides"
# 0, "teamKills"
# 0, "timeSurvived"
# 0, "top10s"
# 0, "vehicleDestroys"
# 0, "walkDistance"
# 0, "weaponsAcquired"
# 0, "weeklyKills"
# 0, "winPoints"
# 0, "wins"
# 0}}}, "relationships"
# {"matchesSolo"
# {"data"
# []}, "matchesSoloFPP"
# {"data"
# []}, "matchesDuo"
# {"data"
# []}, "matchesDuoFPP"
# {"data"
# []}, "matchesSquad"
# {"data"
# []}, "matchesSquadFPP"
# {"data"
# []}, "season"